title: Mastering Web Development through Test-Driven Development
email: akpandeya1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 ğŸš€ Dive into Mastering Web Development through Test-Driven 
  Development! Master the principles & best practices for 
  building robust, scalable, and maintainable web apps. 
  Gain valuable insights and transferable skills, regardless 
  of the tech you use! ğŸ’»ğŸŒ #WebDev #TDD #LearnToCode
github_username: akpandeya
domain: fastapi-celery-tdd.github.io      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://akpandeya.github.io/b  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: fastapi-celery-tdd.github.io     # place folder name if the site is served in a subfolder

# Build settings
theme: minima
plugins:
  - jekyll-feed
